// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.26.0
// source: proto/greet.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GreetClient is the client API for Greet service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GreetClient interface {
	SayHello(ctx context.Context, in *HelloServer, opts ...grpc.CallOption) (*HelloResponse, error)
	Server(ctx context.Context, in *HelloServer, opts ...grpc.CallOption) (Greet_ServerClient, error)
	Client(ctx context.Context, opts ...grpc.CallOption) (Greet_ClientClient, error)
	Bidir(ctx context.Context, opts ...grpc.CallOption) (Greet_BidirClient, error)
}

type greetClient struct {
	cc grpc.ClientConnInterface
}

func NewGreetClient(cc grpc.ClientConnInterface) GreetClient {
	return &greetClient{cc}
}

func (c *greetClient) SayHello(ctx context.Context, in *HelloServer, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/greetservice.greet/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetClient) Server(ctx context.Context, in *HelloServer, opts ...grpc.CallOption) (Greet_ServerClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greet_ServiceDesc.Streams[0], "/greetservice.greet/Server", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetServerClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greet_ServerClient interface {
	Recv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetServerClient struct {
	grpc.ClientStream
}

func (x *greetServerClient) Recv() (*HelloResponse, error) {
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetClient) Client(ctx context.Context, opts ...grpc.CallOption) (Greet_ClientClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greet_ServiceDesc.Streams[1], "/greetservice.greet/client", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetClientClient{stream}
	return x, nil
}

type Greet_ClientClient interface {
	Send(*HelloServer) error
	CloseAndRecv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetClientClient struct {
	grpc.ClientStream
}

func (x *greetClientClient) Send(m *HelloServer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetClientClient) CloseAndRecv() (*HelloResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *greetClient) Bidir(ctx context.Context, opts ...grpc.CallOption) (Greet_BidirClient, error) {
	stream, err := c.cc.NewStream(ctx, &Greet_ServiceDesc.Streams[2], "/greetservice.greet/bidir", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetBidirClient{stream}
	return x, nil
}

type Greet_BidirClient interface {
	Send(*HelloServer) error
	CloseAndRecv() (*HelloResponse, error)
	grpc.ClientStream
}

type greetBidirClient struct {
	grpc.ClientStream
}

func (x *greetBidirClient) Send(m *HelloServer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetBidirClient) CloseAndRecv() (*HelloResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(HelloResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreetServer is the server API for Greet service.
// All implementations must embed UnimplementedGreetServer
// for forward compatibility
type GreetServer interface {
	SayHello(context.Context, *HelloServer) (*HelloResponse, error)
	Server(*HelloServer, Greet_ServerServer) error
	Client(Greet_ClientServer) error
	Bidir(Greet_BidirServer) error
	mustEmbedUnimplementedGreetServer()
}

// UnimplementedGreetServer must be embedded to have forward compatible implementations.
type UnimplementedGreetServer struct {
}

func (UnimplementedGreetServer) SayHello(context.Context, *HelloServer) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedGreetServer) Server(*HelloServer, Greet_ServerServer) error {
	return status.Errorf(codes.Unimplemented, "method Server not implemented")
}
func (UnimplementedGreetServer) Client(Greet_ClientServer) error {
	return status.Errorf(codes.Unimplemented, "method Client not implemented")
}
func (UnimplementedGreetServer) Bidir(Greet_BidirServer) error {
	return status.Errorf(codes.Unimplemented, "method Bidir not implemented")
}
func (UnimplementedGreetServer) mustEmbedUnimplementedGreetServer() {}

// UnsafeGreetServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GreetServer will
// result in compilation errors.
type UnsafeGreetServer interface {
	mustEmbedUnimplementedGreetServer()
}

func RegisterGreetServer(s grpc.ServiceRegistrar, srv GreetServer) {
	s.RegisterService(&Greet_ServiceDesc, srv)
}

func _Greet_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloServer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreetServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/greetservice.greet/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreetServer).SayHello(ctx, req.(*HelloServer))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greet_Server_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloServer)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreetServer).Server(m, &greetServerServer{stream})
}

type Greet_ServerServer interface {
	Send(*HelloResponse) error
	grpc.ServerStream
}

type greetServerServer struct {
	grpc.ServerStream
}

func (x *greetServerServer) Send(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Greet_Client_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServer).Client(&greetClientServer{stream})
}

type Greet_ClientServer interface {
	SendAndClose(*HelloResponse) error
	Recv() (*HelloServer, error)
	grpc.ServerStream
}

type greetClientServer struct {
	grpc.ServerStream
}

func (x *greetClientServer) SendAndClose(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetClientServer) Recv() (*HelloServer, error) {
	m := new(HelloServer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Greet_Bidir_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetServer).Bidir(&greetBidirServer{stream})
}

type Greet_BidirServer interface {
	SendAndClose(*HelloResponse) error
	Recv() (*HelloServer, error)
	grpc.ServerStream
}

type greetBidirServer struct {
	grpc.ServerStream
}

func (x *greetBidirServer) SendAndClose(m *HelloResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetBidirServer) Recv() (*HelloServer, error) {
	m := new(HelloServer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Greet_ServiceDesc is the grpc.ServiceDesc for Greet service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Greet_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "greetservice.greet",
	HandlerType: (*GreetServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greet_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Server",
			Handler:       _Greet_Server_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "client",
			Handler:       _Greet_Client_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "bidir",
			Handler:       _Greet_Bidir_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/greet.proto",
}
