# version: '3'

# services:
#   db:
#     image: mysql:latest
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: password
#     ports:
#       - "3307:3306"  # Map host port 3307 to container port 3306

#   app:
#     build: .
#     restart: always
#     ports:
#       - "8081:8081"
#     depends_on:
#       - db
